GRANT CONNECT ON DATABASE unicorn TO "cycleon_ro";
GRANT CONNECT ON DATABASE unicorn-3rdparty TO "cycleon_ro";
GRANT CONNECT ON DATABASE zebra TO "cycleon_ro";
GRANT USAGE ON SCHEMA public TO "cycleon_ro";
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "cycleon_ro";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "cycleon_ro";
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO "cycleon_ro";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO "cycleon_ro";
